In [1]:

import numpy as np

# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [3]:
a = np.array([1, 2, 3, 4]) #create an array

a + 5

array([6, 7, 8, 9])

In [4]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

**All arithmetic operates elementwise**

In [8]:
b = np.ones(4) + 1  #1,1,1,1
print(b)
print(a)
a - b

[2. 2. 2. 2.]
[1 2 3 4]


array([-1.,  0.,  1.,  2.])

In [ ]:
a * b  #[1,2,3,4] [2,2,2,2]

array([ 2.,  4.,  6.,  8.])

In [11]:
# Matrix multiplication
c = np.diag([1, 2, 3, 4])
print(c * c)  #element by element
print("*****************")
print(c.dot(c)) #matrix mul

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [12]:
c = np.diag([1, 2, 3, 4])
print(c)
d = np.diag([6, 2, 3, 7])
print(d)
d[[1,2]]=5
print(d)
print("------------------")
print(c*d)
print("------------------")
print(c.dot(d))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[6 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 7]]
[[6 0 0 0]
 [5 5 5 5]
 [5 5 5 5]
 [0 0 0 7]]
------------------
[[ 6  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 28]]
------------------
[[ 6  0  0  0]
 [10 10 10 10]
 [15 15 15 15]
 [ 0  0  0 28]]


In [12]:
import numpy as np
np.matmul(c,c)  #matrix mutiplication

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

**comparisions**

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [ ]:
a > b

array([False, False,  True, False], dtype=bool)

In [1]:
import numpy as np
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [2]:
np.array_equal(a, c)

True

**Logical Operations**

In [3]:
a = np.array([1, 1, 0, 0], dtype=bool) #1=true,0=False
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [4]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transcendental functions:**

In [7]:
a = np.arange(5)

np.sin(a)   

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [8]:
np.log(a)

C:\Users\91920\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(a)   #evaluates e^x for each element in a given input

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

**Shape Mismatch**

In [9]:
a = np.arange(4)
print(a.shape)

a + np.array([1, 2])

(4,)


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

**computing sums**

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [7]:
#sum by rows and by columns

x = np.array([[1, 1], [3, 4]])
x

array([[1, 1],
       [3, 4]])

In [8]:
x.sum()

9

In [9]:
x.sum(axis=0)   #columns first dimension

array([4, 5])

In [10]:
x.sum(axis=1)  #rows (second dimension)

array([2, 7])

**Other reductions**

In [3]:
x = np.array([1, 3, 2])
x.min()

1

In [4]:
x.max()

3

In [5]:
x.argmin()# index of minimum element

0

In [4]:
y = np.array([[5, 2], [1, 4]])
print(y.argmin())

2


In [6]:
y.argmax()# index of maximum element

0

**Logical Operations**

In [4]:
np.all([True, True, False]) #0, False

False

In [5]:
np.any([True, False, False]) #True

True

In [13]:
#Note: can be used for array comparisions
a = np.zeros((10, 10))#0 a==0
print(a)
np.any(a != 0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


False

In [24]:
np.all(a == a)

True

In [14]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

**Statistics**

In [15]:
x = np.array([1, 2, 3, 1]) #1,1,2,3
y = np.array([[1, 2, 3], [5, 6, 1]])
print(x.mean())
y.mean()

1.75


3.0

In [19]:
np.median(y) #middle element

2.5

In [ ]:
np.median(y, axis= 1) # last axis

array([ 2.,  5.])

In [ ]:
x.std()          # full population standard dev.

0.82915619758884995

**Example:**

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.


In [3]:
import numpy as np
#load data into numpy array object
data = np.loadtxt('population.txt') #C:/Users/91920/Python/population.txt

In [5]:
'''file=open("population.txt","r") 
print(file.read())
file.close()'''

'file=open("population.txt","r") \nprint(file.read())\nfile.close()'

In [21]:
b=data.max(axis=0)
c=data.argmax(axis=0)
print("max value of hynes = ", b[1])
print("max value of lynax = ", b[2])
print(c)
print(data[c[1]][0])
print("max value of hynes is in year = ", data[c[1]][0])
print("max value of lynax is in year = ",data[c[2]][0])

max value of hynes =  77400.0
max value of lynax =  59400.0
[20  3  4  0]
1903.0
max value of hynes is in year =  1903.0
max value of lynax is in year =  1904.0


In [20]:
data[c[1]][0]

1903.0

In [5]:
x = data[ : ,0:3]
print(x)
y = data[ : , -1:]
print(y)

[[ 1900. 30000.  4000.]
 [ 1901. 47200.  6100.]
 [ 1902. 70200.  9800.]
 [ 1903. 77400. 35200.]
 [ 1904. 36300. 59400.]
 [ 1905. 20600. 41700.]
 [ 1906. 18100. 19000.]
 [ 1907. 21400. 13000.]
 [ 1908. 22000.  8300.]
 [ 1909. 25400.  9100.]
 [ 1910. 27100.  7400.]
 [ 1911. 40300.  8000.]
 [ 1912. 57000. 12300.]
 [ 1913. 76600. 19500.]
 [ 1914. 52300. 45700.]
 [ 1915. 19500. 51100.]
 [ 1916. 11200. 29700.]
 [ 1917.  7600. 15800.]
 [ 1918. 14600.  9700.]
 [ 1919. 16200. 10100.]
 [ 1920. 24700.  8600.]]
[[48300.]
 [48200.]
 [41500.]
 [38200.]
 [40600.]
 [39800.]
 [38600.]
 [42300.]
 [44500.]
 [42100.]
 [46000.]
 [46800.]
 [43800.]
 [40900.]
 [39400.]
 [39000.]
 [36700.]
 [41800.]
 [43300.]
 [41300.]
 [47300.]]


In [7]:
print(y.max())
b=y.argmax()
print(b)

48300.0
0


In [9]:
a=data[b]
print(a[0])
print(a[1])

1900.0


In [9]:
year, hares, lynxes, carrots = data.T #columns to variables
data.T

array([[ 1900.,  1901.,  1902.,  1903.,  1904.,  1905.,  1906.,  1907.,
         1908.,  1909.,  1910.,  1911.,  1912.,  1913.,  1914.,  1915.,
         1916.,  1917.,  1918.,  1919.,  1920.],
       [30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
        22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
        11200.,  7600., 14600., 16200., 24700.],
       [ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
         8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
        29700., 15800.,  9700., 10100.,  8600.],
       [48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
        44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
        36700., 41800., 43300., 41300., 47300.]])

In [ ]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[ 1900.  1901.  1902.  1903.  1904.  1905.  1906.  1907.  1908.  1909.
  1910.  1911.  1912.  1913.  1914.  1915.  1916.  1917.  1918.  1919.
  1920.]


In [ ]:
#The mean population over time
populations = data[:, 1:]
populations

array([[ 30000.,   4000.,  48300.],
       [ 47200.,   6100.,  48200.],
       [ 70200.,   9800.,  41500.],
       [ 77400.,  35200.,  38200.],
       [ 36300.,  59400.,  40600.],
       [ 20600.,  41700.,  39800.],
       [ 18100.,  19000.,  38600.],
       [ 21400.,  13000.,  42300.],
       [ 22000.,   8300.,  44500.],
       [ 25400.,   9100.,  42100.],
       [ 27100.,   7400.,  46000.],
       [ 40300.,   8000.,  46800.],
       [ 57000.,  12300.,  43800.],
       [ 76600.,  19500.,  40900.],
       [ 52300.,  45700.,  39400.],
       [ 19500.,  51100.,  39000.],
       [ 11200.,  29700.,  36700.],
       [  7600.,  15800.,  41800.],
       [ 14600.,   9700.,  43300.],
       [ 16200.,  10100.,  41300.],
       [ 24700.,   8600.,  47300.]])

In [ ]:
#sample standard deviations
populations.std(axis=0)

array([ 20897.90645809,  16254.59153691,   3322.50622558])

In [ ]:
#which species has the highest population each year?

np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

# Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

![title](broadcasting.png)

In [7]:
np.arange(0, 40, 10)

array([ 0, 10, 20, 30])

In [8]:
np.tile(np.arange(0, 40, 10), (3,1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3,1))
print(a)

print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:

b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [ ]:

a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.arange(0, 40, 10)
a.shape


(4,)

In [ ]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

(4, 1)

In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array Shape Manipulation

**Flattening**

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])  
print(a)
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [11]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

**Reshaping**

The inverse operation to flattening:

In [17]:
print(a.shape)
print(a)   #4,3 =12 ,,,, 1*12,,,,2*6 ,,3*4
b=a.reshape((6,1))
print(b)
c=a.reshape((3,2))
print(c)
d=a.reshape((4,4))
print(d)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


ValueError: cannot reshape array of size 6 into shape (4,4)

In [ ]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [ ]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

**Note and       Beware: reshape may also return a copy!:**

In [ ]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
b

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [11]:
import numpy as np
z = np.array([1, 2, 3])
z.shape

(3,)

In [20]:
a=z[np.newaxis,:]
b=z[:,np.newaxis]
print(a.shape)
b.shape

(1, 3)


(3, 1)

In [17]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
b[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

**Dimension Shuffling**

In [ ]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a[0, 2, 1]

5

**Resizing**

In [3]:
a = np.arange(2)
a.resize((8,))
a

array([0, 1, 0, 0, 0, 0, 0, 0])

However, it must not be referred to somewhere else:

In [ ]:
b = a
a.resize((4,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

**Sorting Data**

In [ ]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [ ]:
a[j]

array([1, 2, 3, 4])